version: '3.4'

services:
  telegrambot:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8443
    ports:
      - "8443:8443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    networks:
      - frontend
      - backend
    depends_on: 
      - "redis"
      - "rabbitmq"

  redis:
    command: redis-server --requirepass !Redis2020
    ports:
      - "6379:6379"
    networks:
      - backend
    volumes:
      - redis-data:/data

  rabbitmq:
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "!RabbitMQ2020"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend


volumes:
  redis-data:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge