version: '3.4'

services:
  telegrambot:
    container_name: telegrambot
    hostname: telegrambot
    image: telegrambotwebhook
    build:
      context: .
      dockerfile: TelegramBot.WebHook/Dockerfile

  redis:
    container_name: redis
    hostname: redis
    image: redis

  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3-management
