version: '3.4'

services:
  telegrambot:
    container_name: telegrambot
    hostname: telegrambot
    image: telegrambotwebhook
    build:
      context: .
      dockerfile: TelegramBot.WebHook/Dockerfile

  esbworkersbots:
    container_name: esbworkersbots
    hostname: esbworkersbots
    image: esbworkersbots
    build:
      context: .
      dockerfile: ESB/Workers/ESB.Workers.Bots/Dockerfile

  esbservicesmessaging:
    image: esbservicesmessaging
    build:
      context: .
      dockerfile: ESB/Services/ESB.Services.Messaging/Dockerfile

  redis:
    container_name: redis
    hostname: redis
    image: redis

  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3-management

  mssql:
    container_name: mssql
    hostname: mssql
    image: 'microsoft/mssql-server-linux'
