// <auto-generated />
using System;
using ESB.Data.Context.Bots;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ESB.Data.Migrations.Bots
{
    [DbContext(typeof(BotsContext))]
    [Migration("20200225220925_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ESB.Domain.Entities.Bots.MessageIn", b =>
                {
                    b.Property<Guid>("MessageInId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Messenger")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Moment")
                        .HasColumnType("datetime2");

                    b.Property<string>("Order")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MessageInId");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("ESB.Domain.Entities.Bots.MessageOut", b =>
                {
                    b.Property<Guid>("MessageOutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("MessageInId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Messenger")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MessageOutId");

                    b.HasIndex("MessageInId");

                    b.ToTable("MessageOut");
                });

            modelBuilder.Entity("ESB.Domain.Entities.Bots.MessageOut", b =>
                {
                    b.HasOne("ESB.Domain.Entities.Bots.MessageIn", "MessageIn")
                        .WithMany("MessagesOut")
                        .HasForeignKey("MessageInId");
                });
#pragma warning restore 612, 618
        }
    }
}
